id: IA9361C37
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T14:23:52+00:00'
last_modified: '2022-06-08T03:41:28.974701+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ8075
  title: ལམ་རིམ་འཁྲིད་གསེར་གྱི་ཡང་ཞུན་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E232:
      image_group_id: I1PD96679
      title: ''
      total_pages: 76
      order: 1
      base_file: E232.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
